# This workflow will install Doppler CLI and Firebase tools, then deploy to Firebase

name: Firebase with Doppler CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      - name: Test Doppler CLI
        run: doppler --version
      - name: Setup Doppler CLI
        run: doppler setup --token=${{secrets.DOPPLER_TOKEN}} --no-prompt
      - name: Install Firebase
        run: npm install -g firebase-tools
      - name: Set Firebase Token
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: echo "Set Firebase Token"
      - name: Deploy
        run: npm run deploy
