# This workflow will install Doppler CLI and Firebase tools, then deploy to Firebase

name: Firebase with Doppler CI

on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          # Changes the dependency path to the main package-lock
          cache-dependency-path: ./functions/package-lock.json
      - run: npm ci
        working-directory: ./functions
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      - name: Test Doppler CLI
        run: doppler --version
      - name: Setup Doppler CLI
        run: doppler setup --token=${{secrets.DOPPLER_TOKEN}} --no-prompt
        working-directory: ./functions
      - name: Install Firebase
        run: npm install -g firebase-tools
        working-directory: ./functions
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        # FIREBASE_TOKEN will allow all firebase commands to run with authentication
        run: npm run deploy
        working-directory: ./functions
